name: Develop

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print author detail
        run: |
            echo "The name of the pusher: ${{ github.event.pusher.name }}"
            echo "The email of the pusher: ${{ github.event.pusher.email }}"
            echo "The username of the pusher: ${{ github.event.pusher.username }}"
            echo "The date of the pusher's commit: ${{ github.event.pusher.date }}"
