name: Develop

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print author detail
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.head_commit) }}
        run: |
          echo "$GITHUB_CONTEXT"
