name: Develop

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print author detail
        run: |
            echo "The name of the pusher: ${{ github.event.pusher }}"
            echo "The email of the pusher: ${{ github.event.base }}"
